name: 'GitHub issue tracker'
description: 'An issue tracker action'
inputs:
  github-token:
    description: 'A GitHub token'
    required: true
outputs:
  actioncloud-badge: # id of output
    description: 'The badge url of a ActionCloud Page'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'trending-up'
  color: 'purple'
